// generated by mBlock5 for MegaPi
// codes make you happy

#include <MePS2.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
//#include "src/MeSingleLineFollower.h"
//#include "src/MeCollisionSensor.h"
//#include "src/MeBarrierSensor.h"
//#include "src/MeNewRGBLed.h"
#include <MeMegaPi.h>

MeMegaPiDCMotor motor_1(1);
MeMegaPiDCMotor motor_9(9);
MeMegaPiDCMotor motor_2(2);
MeMegaPiDCMotor motor_10(10);
MeMegaPiDCMotor motor_3(3);
MeMegaPiDCMotor motor_11(11);
MeMegaPiDCMotor motor_4(4);
MeMegaPiDCMotor motor_12(12);
double angle_rad = PI/180.0;
double angle_deg = 180.0/PI;

const int JOYSTICK_LX = 2;
const int JOYSTICK_LY = 4;
const int JOYSTICK_RX = 6;
const int JOYSTICK_RY = 8;
const float MOTOR_LIMIT = 0.50;  // Max. 50%
const float NEG = -1.0;
const float POS = 1.0;


MePS2 MePS2(PORT_15);

void _delay(float seconds) {
  if(seconds < 0.0){
    seconds = 0.0;
  }
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  MePS2.begin(115200);
  TCCR1A = _BV(WGM10);
  TCCR1B = _BV(CS11) | _BV(WGM12);
  TCCR2A = _BV(WGM21) | _BV(WGM20);
  TCCR2B = _BV(CS21);
 Serial.begin(115200);
}

void _loop() {
  MePS2.loop();
}

// MePS2.MeAnalog(2) is the left stick X; 4 is Y
// 6 is right stick x; 8 is Y.
// Stick values are -255 to 255.
// Port 1A = front right (motor 1)
// Port 1B = back right (motor 9)
// Port 2A = back left (motor 2)
// Port 2B = front left (motor 10)

// 255 means clockwise if you're looking at the wheel


void loop() {
//  Serial.println(val);
//  if(MePS2.ButtonPressed(9)){
//
//      motor_1.run(0);
//      motor_9.run(0);
//      motor_2.run(0);
//      motor_10.run(0);
//      motor_3.run(0);
//      motor_11.run(0);
//      motor_4.run(0);
//      motor_12.run(0);
//
//  }

  // Left-right slide
  float lx_lf = NEG * (MePS2.MeAnalog(JOYSTICK_LX));
  float lx_lr = POS * (MePS2.MeAnalog(JOYSTICK_LX));
  float lx_rf = NEG * (MePS2.MeAnalog(JOYSTICK_LX));
  float lx_rr = POS * (MePS2.MeAnalog(JOYSTICK_LX));
  
//  motor_10.run(left_front_val);  // left front
//  motor_2.run(left_rear_val);   // left rear
//  motor_1.run(right_front_val);   // right front
//  motor_9.run(right_rear_val);   // right rear
//  Serial.println(String(left_front_val) + " " + String(left_rear_val) + " " + String(right_front_val) + " " + String(right_rear_val));



 // up-down-slide
  float ly_lf = NEG * (MePS2.MeAnalog(JOYSTICK_LY));
  float ly_lr = NEG * (MePS2.MeAnalog(JOYSTICK_LY));
  float ly_rf = POS * (MePS2.MeAnalog(JOYSTICK_LY));
  float ly_rr = POS * (MePS2.MeAnalog(JOYSTICK_LY));

  float lf = (lx_lf + ly_lf) * MOTOR_LIMIT;
  float lr = (lx_lr + ly_lr) * MOTOR_LIMIT;
  float rf = (lx_rf + ly_rf) * MOTOR_LIMIT;
  float rr = (lx_rr + ly_rr) * MOTOR_LIMIT;
  
  motor_10.run(lf);  // left front
  motor_2.run(lr);   // left rear
  motor_1.run(rf);   // right front
  motor_9.run(rr);   // right rear

  _loop();
}
